Repository LeskoIam/GMS, pull requests merged in 2024-06, with the labels that each got.

#6 Adds new Planting join model
  .gitignore
  gms_app/migrations/0007_add_planting.py
  gms_app/migrations/0008_alter_plantpreset_options.py
  gms_app/models.py
  gms_app/tests.py
Labels: dev

#8 Adding bootstrap5 with better views.
  .gitignore
  dev_requirements.txt
  gms/settings.py
  gms_app/migrations/0007_add_planting.py
  gms_app/migrations/0008_alter_plantpreset_options.py
  gms_app/models.py
  gms_app/templates/base.html
  gms_app/templates/garden_detail.html
  gms_app/templates/garden_list.html
  gms_app/templates/home.html
  gms_app/tests.py
  pyproject.toml
Labels: dev

#14 Fixed verbose names for PlantPreset and improved Planting string representation.
  gms_app/admin.py
  gms_app/models.py
  gms_app/tests.py
Labels: dev

#16 Refactoring tests - simplified test data and tests
  .gitignore
  tests/models/test_models_gms_app.py
Labels: dev

#19 [#10] Added basic tests for view
  gms_app/models.py
  gms_app/views.py
  tests/conftest.py
  tests/models/test_models_gms_app.py
  tests/tests.md
  tests/views/__init__.py
  tests/views/test_views_gms_app.py
Labels: tests

#23 Fixed Planting model to only allow one plant per unique location
  gms_app/migrations/0009_alter_plantpreset_options_and_more.py
  gms_app/models.py
  tests/models/test_models_gms_app.py
Labels: fix

#26 [#25] Adding form for adding Plants.
  gms_app/forms.py
  gms_app/models.py
  gms_app/templates/base.html
  gms_app/templates/forms/add_plant_form.html
  gms_app/templates/garden_list.html
  gms_app/urls.py
  gms_app/views.py
  tests/views/test_views_gms_app.py
Labels: enhancement, dev

#29 [#28] Adding form for linking Plants to GardenBeds.
  gms_app/forms.py
  gms_app/templates/base.html
  gms_app/templates/forms/add_plant_to_garden_bed_form.html
  gms_app/urls.py
  gms_app/views.py
  tests/views/test_views_gms_app.py
Labels: enhancement, dev

#34 [#32] Added location field to GardenBed model.
  gms_app/migrations/0011_gardenbed_location.py
  gms_app/models.py
  gms_app/templates/garden_detail.html
Labels: enhancement, dev
